language: node_js
notifications:
	- email: guisequeira@hotmail.com
node_js:
- 0.10
service:
- mongodb
env:
	global:
		- NODE_ENV: test
addons:
	souce_connect: true
before_install:
- npm install -g bower@1.3
- npm install -g grunt-cli@0.1
- npm install -g karma-cli@0.0
- npm install -g protractor@1.5
- webdriver-manager update
- bower install
before_script:
- npm install
- node test/data.js
- grunt
- cd dist
script:
- karma start config/karma.config.js --single-run --browsers PhantomJS
- node server &
- protractor config/protractor.js


